sql = """SELECT * FROM eclinical_study;"""
select_sqls = [sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql]
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql,
            # sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql, sql
            # ]
database_info_dict = {
    "host": "dev-03-instance-1.c9qe4y0vrvda.rds.cn-northwest-1.amazonaws.com.cn",
    "user": "root",
    "port": 3306,
    "pwd": "8YTJWOuA7XRK17wRQnw4",
    "database": "eclinical_edc_dev_863"

}